Bookstore: add reducers and actions
khanh-devos/rjs-bookstore-khanh pull request #2
Opened 2023-07-24 15:30 UTC by khanh-devos

### Tasks in this activity:
- Config a new store, create BookReducer and CategoryReducer.
- Add the new store to the app.
- Create a new folder Redux to contain the two new reducers.
- Create two actions 'addBook' and 'removeBook' inside BookReducer.
- Apply useSelector and useDispatch to modify AddNewBook and BookItem.

2023-07-24 15:49 UTC, Ibizugbe requested changes
Hi @khanh-devos 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/khanh-devos/rjs-bookstore-khanh/assets/64643995/b8d7efa5-1fb2-4946-8513-4b3d4d4341b2)


Good job so far!👍🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] The files structure follows the duck pattern👍🏼.
- [x] @reduxjs/toolkit & react-redux are present in package.json file👍🏼.
- [x] A book slice has been created with an initiall state and a reducer that performs the add and remove actions👍🏼.
- [x] The configure store has a reducer that holds the book and categories reducer👍🏼.



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-24 15:49 UTC, Ibizugbe commented on src/redux/categories/categorySlice.js
> +  reducers: {},
Nice job so far😉. Just as required for this milestone, we ought to create a reducer that checks the status and always returns "Under construction" 😉. Kindly do well to implement this in the reducers👍🏼.

<img width="1019" alt="image" src="https://github.com/khanh-devos/rjs-bookstore-khanh/assets/64643995/4686aa5e-9887-4a4b-af3e-8a01288c107f">

2023-07-24 16:40 UTC, OyePriscilla approved these changes
Hi @khanh-devos 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
`categoryReducer` status updated ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 03:31 UTC, khanh-devos commented
Hi @OyePriscilla 
Thank you for your quick review.

2023-07-25 03:31 UTC, merged